### ISSUE TITLE
Cargo.toml files appear to declare the wrong license

### ISSUE THREAD

**Issue by PatchMixolydic** [tim-harding/kanjidic_utilities#1]
According to [README.md](https://github.com/tim-harding/kanjidic_utilities/blob/353ea5d7f0e8bba3302d26405962921defb492de/README.md),

> This project is released under the [Creative Commons Attribution-ShareAlike 3.0](https://creativecommons.org/licenses/by-sa/3.0/legalcode) license as per the [EDRDG license statement](http://www.edrdg.org/edrdg/licence.html).

However, the Cargo manifests for each crate claim that they're licensed under the Creative Commons Attribution-Noncommercial-ShareAlike 3.0 license:
https://github.com/tim-harding/kanjidic_utilities/blob/353ea5d7f0e8bba3302d26405962921defb492de/kanjidic_parser/Cargo.toml#L5

**Comment by tim-harding** [comment]
Thank you! I fixed up the license and noticed a bunch of new errors in recent Rust versions, so I cleaned those up as well.
